#!/bin/bash

# 定义命令数组
commands=(
    # "python run_texture.py --config ./config/1.yaml"
    # "python run_texture.py --config ./config/3.yaml"
    # "python run_texture.py --config ./config/4.yaml"
    # "python run_texture.py --config ./config/5.yaml"
    # "python run_texture.py --config ./config/5-2.yaml"
    # "python run_texture.py --config ./config/6.yaml"
    # "python run_texture.py --config ./config/6-2.yaml"
    # "python run_texture.py --config ./config/7.yaml"
    # "python run_texture.py --config ./config/8.yaml"
    # "python run_texture.py --config ./config/9.yaml"
    # "python run_texture.py --config ./config/10.yaml"
    # "python run_texture.py --config ./config/11.yaml"
    # "python run_texture.py --config ./config/12.yaml"
    # "python run_texture.py --config ./config/14.yaml"
    # "python run_texture.py --config ./config/16-2.yaml"
    # "python run_texture.py --config ./config/21.yaml"
    # "python run_texture.py --config ./config/22.yaml"
    # "python run_texture.py --config ./config/23.yaml"
    # "python run_texture.py --config ./config/24.yaml"
    # "python run_texture.py --config ./config/25.yaml"
    # "python run_texture.py --config ./config/26.yaml"
    # "python run_texture.py --config ./config/27.yaml"
    # "python run_texture.py --config ./config/28.yaml"
    # "python run_texture.py --config ./config/28-2.yaml"
    # "python run_texture.py --config ./config/29.yaml"
    # "python run_texture.py --config ./config/30.yaml"
    # "python run_texture.py --config ./config/31.yaml"
    # "python run_texture.py --config ./config/32.yaml"
    # "python run_texture.py --config ./config/cupcake.yaml"
    # "python run_texture.py --config ./config/dog.yaml"
    # "python run_texture.py --config ./config/dog-2.yaml"
    # "python run_texture.py --config ./config/plaid-skirt.yaml"
    # "python run_texture.py --config ./config/pubdog.yaml"
    # "python run_texture.py --config ./config/woman-coats.yaml"
    # "python run_texture.py --config ./config/nascar.yaml"
    # "python run_texture.py --config ./config/napoleon.yaml"
    # "python run_texture.py --config ./config/Wall-E.yaml"
    # "python run_texture.py --config ./config/bear.yaml"
    # "python run_texture.py --config ./config/rabbit.yaml"
    # "python run_texture.py --config ./config/gloves.yaml"
    # "python run_texture.py --config ./config/lego.yaml"
    # "python run_texture.py --config ./config/lego_girl.yaml"
    # "python run_texture.py --config ./config/person.yaml"
    # "python run_texture.py --config ./config/person-2.yaml"
    # "python run_texture.py --config ./config/globe.yaml"
    # "python run_texture.py --config ./config/globe-2.yaml"
    # "python run_texture.py --config ./config/dragon.yaml"
    # "python run_texture.py --config ./config/statue.yaml"
    # "python run_texture.py --config ./config/handbag.yaml"
    # "python run_texture.py --config ./config/backpack.yaml"
    # "python run_texture.py --config ./config/luggage-box.yaml"
    # "python run_texture.py --config ./config/Provost.yaml"
    "python run_texture.py --config ./config/camera.yaml"
    "python run_texture.py --config ./config/car.yaml"
    "python run_texture.py --config ./config/spider_lego.yaml"
    "python run_texture.py --config ./config/shiba.yaml"
)

# 使用 for 循环依次运行命令
for cmd in "${commands[@]}"; do
    echo "Running: $cmd"
    $cmd  # 执行命令
    echo "Finished running: $cmd"
    echo "--------------------------------"
done